// <auto-generated />
using System;
using Crud.Back.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crud.Back.Infra.Data.Migrations
{
    [DbContext(typeof(CrudBackContext))]
    [Migration("20250324234900_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Crud.Back.Domain.Entities.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FormationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdStyle")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdStyle");

                    b.ToTable("Band", (string)null);
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.BandMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdBand")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMember")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdBand");

                    b.HasIndex("IdMember");

                    b.ToTable("BandMember", (string)null);
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Instrument", (string)null);
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("IdInstrument")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IdInstrument");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.Style", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Style", (string)null);
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.Band", b =>
                {
                    b.HasOne("Crud.Back.Domain.Entities.Style", "Style")
                        .WithMany("Bands")
                        .HasForeignKey("IdStyle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Style");
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.BandMember", b =>
                {
                    b.HasOne("Crud.Back.Domain.Entities.Band", "Band")
                        .WithMany("BandMembers")
                        .HasForeignKey("IdBand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crud.Back.Domain.Entities.Member", "Member")
                        .WithMany("BandMembers")
                        .HasForeignKey("IdMember")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.Member", b =>
                {
                    b.HasOne("Crud.Back.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Members")
                        .HasForeignKey("IdInstrument")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.Band", b =>
                {
                    b.Navigation("BandMembers");
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.Member", b =>
                {
                    b.Navigation("BandMembers");
                });

            modelBuilder.Entity("Crud.Back.Domain.Entities.Style", b =>
                {
                    b.Navigation("Bands");
                });
#pragma warning restore 612, 618
        }
    }
}
